apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tdemo-dev.dev.tap.20231219152217.0.0+build.17cb7cd
spec:
  refName: tdemo-dev.dev.tap
  version: 20231219152217.0.0+build.17cb7cd
  releaseNotes: |
    Release v20231219152217.0.0+build.17cb7cd of package tdemo-dev.dev.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.harborlab.fynesy.net/tap/tdemo-dev-dev-bundle@sha256:61b2483049c2edcb6157dc94b6ae6ce5ac6f8f8e4bcdaccf04e06ae153f833f2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

