apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tdemo-dev.dev.tap.20231219152257.0.0+build.17cb7cd
spec:
  refName: tdemo-dev.dev.tap
  version: 20231219152257.0.0+build.17cb7cd
  releaseNotes: |
    Release v20231219152257.0.0+build.17cb7cd of package tdemo-dev.dev.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.harborlab.fynesy.net/tap/tdemo-dev-dev-bundle@sha256:6db7c92dad47f12e3e9db47c01f77d0111dae6496dde8b7e554d8e6223bcd1a1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

